version: '3.8'

services:
  keycloak:
    image: osamamahmoudh/my-keycloak:25.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword

      #database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword


      KC_HOSTNAME: 192.168.0.159
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    volumes:
      - /home/osama/HOME/GYOOM/keycloak/production-mode/certs:/etc/x509/https
    networks:
      - keycloak-network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  pg_data:
